# Generated by Django 4.1.3 on 2022-12-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppContainerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_short_id", models.CharField(max_length=12, unique=True)),
                ("container_name", models.CharField(max_length=255)),
                ("container_image", models.CharField(max_length=255)),
                (
                    "container_command",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("container_envs", models.JSONField(default=dict)),
                ("container_status", models.CharField(max_length=100)),
                ("container_logs", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.app",
                    ),
                ),
            ],
        ),
    ]
