# Generated by Django 4.1.3 on 2022-12-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appcontainerhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcontainerhistory',
            name='container_status',
        ),
    ]
